[package]
name = "pocket"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
clap.workspace = true
hex.workspace = true
pocket-core = { path = "../pocket-core" }
pocket-oci = { path = "../pocket-oci" }
pocket-runtime = { path = "../pocket-runtime" }
pocket-store = { path = "../pocket-store" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
pocket-protocol = { path = "../pocket-protocol" }
sha2.workspace = true
tempfile.workspace = true

[lints]
workspace = true
